# Generated by Django 2.2.15 on 2020-08-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=100, unique=True, verbose_name='Регистрационный номер заказа')),
                ('on_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования заказа')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Заказ активен')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Идентификатор товара')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Количество товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена за единицу измерения товара для данного заказа')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Деталь заказа активна')),
                ('hdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.OrderHeaders', verbose_name='Идентификатор товара')),
            ],
        ),
    ]
